import mongoose from 'mongoose';

/**
 * ============================================================================
 * MONITORED REPO MODEL — Repos with Active Webhook Monitoring
 * ============================================================================
 *
 * When a user enables monitoring on a GitHub repo, we:
 * 1. Register a webhook on that repo via GitHub's REST API
 * 2. Generate a unique webhook secret for HMAC signature verification
 * 3. Store this record so we can:
 *    - Look up the secret when we receive a webhook event (for validation)
 *    - Find the user who owns the repo (to decrypt their GitHub token)
 *    - Delete the webhook if the user disables monitoring
 *
 * WHY A UNIQUE SECRET PER REPO:
 * If we used a single global secret for all webhooks, an attacker who
 * discovers the secret for one repo could forge webhooks for ALL repos.
 * With per-repo secrets, a compromise is isolated to that single repo.
 *
 * WEBHOOK LIFECYCLE:
 * 1. User enables monitoring → we POST /repos/{owner}/{repo}/hooks → GitHub
 *    returns a webhookId → we store it here
 * 2. GitHub sends events → we validate the signature using the stored secret
 * 3. User disables monitoring → we DELETE /repos/{owner}/{repo}/hooks/{id}
 *    using the stored webhookId → we deactivate this record
 * ============================================================================
 */

const monitoredRepoSchema = new mongoose.Schema(
  {
    // Reference to the User who owns this monitored repo
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    // Full repo name in "owner/repo" format (e.g., "octocat/hello-world")
    // This is what GitHub sends in webhook payloads
    repoFullName: {
      type: String,
      required: true,
      index: true,
    },

    // GitHub's numeric repo ID — permanent identifier
    repoId: {
      type: Number,
      required: true,
    },

    // The webhook ID returned by GitHub when we register the hook
    // We need this to delete the webhook later
    webhookId: {
      type: Number,
      required: true,
    },

    // Unique HMAC secret for this repo's webhook
    // Used to verify X-Hub-Signature-256 header on incoming webhook events
    // Generated by crypto.randomBytes(32).toString('hex') — see encryption.js
    webhookSecret: {
      type: String,
      required: true,
    },

    // Whether monitoring is currently active
    // Setting to false keeps the record but stops processing events
    isActive: {
      type: Boolean,
      default: true,
    },

    // Timestamp of the last webhook event received for this repo
    lastEventAt: {
      type: Date,
      default: null,
    },

    // Repo metadata for display purposes
    repoMeta: {
      description: String,
      language: String,
      defaultBranch: String,
      isPrivate: Boolean,
      htmlUrl: String,
    },
  },
  {
    collection: 'monitored_repos',
    timestamps: true,
  }
);

// Compound index: a user can only monitor a repo once
monitoredRepoSchema.index({ userId: 1, repoFullName: 1 }, { unique: true });

export default mongoose.model('MonitoredRepo', monitoredRepoSchema);
